### ISSUE TITLE
Quotes in datatype names or fields don't get escaped

### ISSUE THREAD

**Issue by mgsloan** [mikeplus64/aeson-flowtyped#4]
If you have a type like

```
data Should = Should | Shouldn't
```

The tag for the latter will look like `tag: 'Shouldn't'` - need to escape single quotes

**Comment by mikeplus64** [comment]
also should do something about type names themselves that have quotations in them, or if you try to make flowtypes for a type operator, hm...

**Comment by mikeplus64** [comment]
This is fixed now, apostrophes get replaced with `_`. No handling of type operators though.
