### ISSUE TITLE
Consider listing limitations in the module documentation or readme

### ISSUE THREAD

**Issue by mgsloan** [mikeplus64/aeson-flowtyped#5]
Hey, cool project!   Unfortunately, after sinking in quite a bit of effort, figured out it has some issues that make it unusable for my usecase.  It would be good to document these in the haddock / readme:

* Polymorphism doesn't work (#1)

* Looks like dependencies check will infinite loop on mutual recursion

* The minor issue of quotes in the datatype is definitely a problem, but probably easily resolved #4

It would be good to document that the package is work-in-progress or partially complete, because, well, someone like me might come along and spend hours trying to get it to work for their usecase.

I would try to fix it (already fixed some things in https://github.com/mikeplus64/aeson-flowtyped/pull/3), but the use of generics / functor fixpoints / functor composition make it a real head scratcher.  I think it would be better to:

* Use TH instead of generics. Using aeson's TH would be a good starting point, because then you can be sure the logic is related.
* Use a plain ol recursive datatype for flow types, and avoid pattern synonyms.  Using fancy stuff makes it much less likely that others will understand and contribute.

**Comment by mikeplus64** [comment]
>Use TH instead of generics. Using aeson's TH would be a good starting point, because then you can be sure the logic is related.

It would be nice to reuse TH code from aeson, but I don't really see any exports from there that can be used?

>Use a plain ol recursive datatype for flow types, and avoid pattern synonyms. Using fancy stuff makes it much less likely that others will understand and contribute.

Doable but likely a lot of effort... Right now `FlowTypeF` is only put to real use with the `Info` tags that are passed around, which are only used for detecting nullary constructor alternatives like `data A = A | B | C`.

**Comment by mgsloan** [comment]
> It would be nice to reuse TH code from aeson, but I don't really see any exports from there that can be used?

It'd be more of a copy+modify kind of re-use.

RE the fixpoint stuff I was mostly just a bit grumpy because I couldn't figure out how to get this working for my usecase.  It seems likely that I will revisit generating flow types sometime in the next month or two, and at that point will either try to get this working with polymorphism or use TH

Closing this, thanks for your response!

**Comment by mikeplus64** [comment]
hm, I can't remember why I didn't use this in the first place, but `recursion-schemes` [has got a `makeBaseFunctor` ](https://www.stackage.org/haddock/lts-11.11/recursion-schemes-5.0.2/Data-Functor-Foldable-TH.html) which would generate `FlowTypeF` from a simpler/more idiomatic `data FlowType = ...` definition. That would probably simplify all the code that doesn't need "extra stuff" like `FlowTypeI` does.
